Default: &defaults
  database: yesod-angular-sqlite.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-angular-sqlite_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-angular-sqlite_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-angular-sqlite_production.sqlite3
  poolsize: 100
  <<: *defaults
